name: "ml2mqtt"
description: "Machine learning for MQTT"
version: "1.1.6"
slug: "ml2mqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 5000
panel_icon: "mdi:web"
panel_title: "ml2mqtt"
options:
  mqtt_server: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "mqtt"
  mqtt_password: "mqtt"
schema:
  mqtt_server:
    type: str
    default: "core-mosquitto"
    description: "The host name or IP address of the MQTT server"
  mqtt_port:
    type: int
    default: 1883
    description: "The port of the MQTT server"
  mqtt_username:
    type: str
    default: "mqtt"
    description: "The username used to access the MQTT server"
  mqtt_password:
    type: str
    default: "mqtt"
    description: "The password used to access the MQTT server"