name: "ml2mqtt"
description: "Machine learning for MQTT"
version: "1.2.21"
slug: "ml2mqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 5000
panel_icon: "mdi:fish"
panel_title: "ml2mqtt"
options:
  mqtt-server: "core-mosquitto"
  mqtt-port: 1883
  mqtt-username: "mqtt"
  mqtt-password: "mqtt"
schema:
  mqtt-server: "str"
  mqtt-port: "int"
  mqtt-username: "str"
  mqtt-password: "str"