name: "ml2mqtt"
description: "Machine learning for MQTT"
version: "1.1.4"
slug: "ml2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 5000
panel_icon: "mdi:web"
panel_title: "ml2mqtt"
